### ISSUE TITLE
[Suggestion] Prefixes, Additional Options and Some Other Things

### ISSUE THREAD

**Issue by Rage-GitHub** [DisabledMallis/KitEngine#2]
SUGGESTION
---------
I like the concept of this plugin and it looks good, but I do have to say that there are some things that can help improve it. A prefix option, maybe something like the image below would be a nice addition as the messages currently are boring.

It would also be nice if we can set our own items in the Kit so maybe some fillers like glass panes and also the ability to change the slot size of the GUI, as a full chest size is not really necessary.

Also, maybe if possible add a item selection instead because I know people will complain and want that so just getting ahead of the game and getting it out there.

It would be nice if we can also edit the kits positions in the GUI so we're able to arrange them in any order we want.

![image](https://user-images.githubusercontent.com/17907584/61666048-8eafa300-aca4-11e9-9728-4fe3b88a3569.png)

**Comment by DisabledMallis** [comment]
To help myself stay organized im going to make a checklist, correct me if i make a mistake or smth

- Prefix option
- Custom items in kit gui
- custom positioning in kit gui
- item selection...?

I'm confused about the prefix thing and the item selection, could you elaborate on those?

**Comment by Rage-GitHub** [comment]
> To help myself stay organized im going to make a checklist, correct me if i make a mistake or smth
> 
> * Prefix option
> * Custom items in kit gui
> * custom positioning in kit gui
> * item selection...?
> 
> I'm confused about the prefix thing and the item selection, could you elaborate on those?

Looks all right, for the item selection I mean a GUI displaying every usable block for an icon of the kit.

**Comment by DisabledMallis** [comment]
item selection finished, now to do the other 3

**Comment by DisabledMallis** [comment]
prefix done

**Comment by DisabledMallis** [comment]
Do you have any suggestions for how the other 2 should work & be set up? Im kinda stumped on designing that.

**Comment by DisabledMallis** [comment]
Pretty much done with it all, next update will have everything. If you want to try this ahead of time simply clone this repo and use 'mvn clean package' or 'mvn package' to build it & youll have yourself the gui customizations and all

**Comment by DisabledMallis** [comment]
Finished the release. Everything was added
